import type { NextPage } from 'next'
import Head from 'next/head'
import Test from "../components/Test";



const Home: NextPage = () => {
  return (
    <div className='wrap'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Test />
    

      <footer>
      </footer>
    </div>
  )
}

export default Home
